Vagrant.configure("2") do |config|
   config.vm.box = "centos/7"
   config.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 1
    end

config.vm.define "zabbix-server" do |wordpress|
    wordpress.vm.network "public_network", ip: "192.168.1.86"
    wordpress.vm.network "forwarded_port", guest:8666, host: 8666
    wordpress.vm.synced_folder ".configs", "volume/zabbix-storage"
    end
end