$zabbix_script = <<-SCRIPT
sudo yum update
sudo yum install -y kernel-headers kernel-devel --disableexcludes=all
sudo rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
sudo yum clean all
sudo yum install -y zabbix-server-mysql zabbix-agen
sudo yum install -y centos-release-scl
sudo yum install -y zabbix-web-mysql-scl zabbix-apache-conf-scl
SCRIPT

$mysql_script = <<-SCRIPT
mysql -uroot -p
password
mysql> create database zabbix character set utf8 collate utf8_bin;
mysql> create user zabbix@localhost identified by 'password';
mysql> grant all privileges on zabbix.* to zabbix@localhost;
mysql> quit;
SCRIPT

Vagrant.configure("2") do |config|
   config.vm.box = "bento/centos-8"
   config.vm.provider "virtualbox" do |vb|
       vb.memory = 1024
       vb.cpus = 1
    end

config.vm.define "zabbix-server" do |zabbix|
    zabbix.vm.network "public_network", ip: "192.168.1.86",  bridge: "wlp6s0"
    zabbix.vm.network "forwarded_port", guest:6666, host: 6666
#    zabbix.vm.synced_folder ".configs", "/home/vagrant/zabbix-stuff"

#    zabbix.vm.provision "shell",
#    inline: $zabbix_script

#    zabbix.vm.provision "shell",
#    inline: $mysql_script
    end
end