Vagrant.configure("2") do |config|
   config.vm.box = "centos/7"
   config.vm.provider "virtualbox" do |vb|
       vb.memory = 1024
       vb.cpus = 1
    end

config.vm.define "zabbix-server" do |zabbix|
    zabbix.vm.network "public_network", ip: "192.168.1.86"
    zabbix.vm.network "forwarded_port", guest:8666, host: 8666

    zabbix.vm.provision "shell", path: "zabbix-script-centos.sh"
    end
end