$zabbix_script = <<-SCRIPT
cd /home/vagrant/zabbix-stuff/scripts && sudo chmod +x zabbix-script.sh && ./zabbix-script.sh
sudo chmod +x mysql-script.sh && ./mysql-script.sh
cd ..
sudo cat zabbix_server.conf > /etc/zabbix/zabbix_server.conf
sudo cat php.ini > /etc/php/7.2/apache2/php.ini
sudo systemctl restart zabbix-server zabbix-agent apache2
sudo systemctl enable zabbix-server zabbix-agent apache2

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end

config.vm.define "zabbix-server" do |zabbix|
    zabbix.vm.network "public_network", ip: "192.168.1.86",  bridge: "wlp6s0"
    zabbix.vm.network "forwarded_port", guest:8666, host: 8666
    zabbix.vm.synced_folder ".configs", "/home/vagrant/zabbix-stuff"

    #zabbix.vm.provision "shell",
    #inline: $zabbix_script
    end
end