apiVersion: v1
kind: Pod
metadata:
  name: sitema-noticias
  labels:
    app: sitema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-configmap