version: "3"
services:
  broker:
    container_name: mqtt
    image: levimurici/mqtt
    volumes:
      - /mosquitto:/etc/mosquitto
    networks:
      - rede-docker
    ports:
      - "1883:1883"
      - "9001:9001"

  node-red:
    container_name: node-red
    image: levimurici/node-red
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    user: "0"
    networks:
      - rede-docker
    depends_on:
      - broker

volumes:
  node-red-data:

networks:
 rede-docker:
   driver: bridge
