apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pv
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  volumes:
    - name: test-pod-storage
      persistentVolumeClaim:
        ## PVC-NAME
        claimName: claim1-teste
  containers:
    - name: test-pod-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pod-pv-storage